name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Gellix
    fonts:
    - asset: fonts/Gellix-Regular.ttf
      weight: 500
    - asset: fonts/Gellix-Medium.ttf
      weight: 600
    - asset: fonts/Gellix-Bold.ttf
      weight: 700
  assets:
  - assets/svg/